### ISSUE TITLE
Syntax error in setup.py

### ISSUE THREAD

**Issue by frobnitzem** [LLNL/zfp#233]
Syntax error (maybe misplaced parentheses)?

https://github.com/LLNL/zfp/blob/5c976d8da013988174f931845862b6f94119cade/setup.py#L14

```
% pip install --no-build-isolation 'git+https://github.com/LLNL/zfp.git@1.0.1'
Collecting git+https://github.com/LLNL/zfp.git@1.0.1
  Cloning https://github.com/LLNL/zfp.git (to revision 1.0.1) to /tmp/pip-req-build-aycbhn7n
  Running command git clone --filter=blob:none --quiet https://github.com/LLNL/zfp.git /tmp/pip-req-build-aycbhn7n
  Running command git checkout -q f40868a6a1c190c802e7d8b5987064f044bf7812
  Resolved https://github.com/LLNL/zfp.git to commit f40868a6a1c190c802e7d8b5987064f044bf7812
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [7 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-req-build-aycbhn7n/setup.py", line 14
          libraries=["zfp"], library_dirs=["build/lib64", "build/lib/Release"]), language_level = "3"]
                                                                                 ^^^^^^^^^^^^^^^^^^^^
      SyntaxError: invalid syntax. Maybe you meant '==' or ':=' instead of '='?
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.
```

I'm using python 3.10.12 and numpy 2.0.0.

**Comment by lindstro** [comment]
@frobnitzem Thanks for filing this issue.  We're aware of this; see discussion [here](https://github.com/LLNL/zfp/issues/201#issuecomment-1866151608) and more recently in #231.  I'm trying to figure out the original intent and how to correct this.  I have minimal Python expertise, so any suggestions would be welcome.
